# Generated by Django 4.2.3 on 2023-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="lms_id",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
