# Generated by Django 4.2.3 on 2023-07-25 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("logika_general", "0002_group_lms_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lms_location_name", models.CharField(max_length=255)),
                ("one_c_location_name", models.CharField(max_length=255)),
                ("status", models.CharField(default="open", max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(default="new", max_length=16),
        ),
    ]
