# Generated by Django 4.2.3 on 2023-07-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_general", "0003_location_notification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="client_manager",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
