# Generated by Django 4.2.3 on 2023-10-24 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "logika_general",
            "0006_regionalmanagerprofile_territorialmanagerprofile_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientmanagerprofile",
            old_name="login_key",
            new_name="auth_token",
        ),
        migrations.RenameField(
            model_name="regionalmanagerprofile",
            old_name="login_key",
            new_name="auth_token",
        ),
        migrations.RenameField(
            model_name="territorialmanagerprofile",
            old_name="login_key",
            new_name="auth_token",
        ),
    ]
