# Generated by Django 4.2.3 on 2023-10-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "logika_general",
            "0007_rename_login_key_clientmanagerprofile_auth_token_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmanagerprofile",
            name="login_timestamp",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="regionalmanagerprofile",
            name="login_timestamp",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="territorialmanagerprofile",
            name="login_timestamp",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
