# Generated by Django 4.2.3 on 2023-08-01 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logika_auth", "0002_teacherprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="TeacherProfile",
        ),
        migrations.DeleteModel(
            name="TutorProfile",
        ),
    ]
