# Generated by Django 4.2.3 on 2023-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0003_remove_teacherprofile_related_tutor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="one_c_ids",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
