# Generated by Django 4.2.3 on 2023-08-02 17:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0004_teacherprofile_one_c_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mistakes", models.CharField(max_length=256)),
                (
                    "problems",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2), size=None
                    ),
                ),
                ("additional_problems", models.CharField(max_length=1024)),
                ("predicted_churn", models.CharField(max_length=256)),
                ("technical_problems", models.CharField(max_length=1024)),
                ("km_work_comment", models.CharField(max_length=1024)),
                ("tutor_work_comment", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="logika_teachers.teacherprofile",
                    ),
                ),
            ],
        ),
    ]
