# Generated by Django 4.2.3 on 2023-08-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0005_teacherfeedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherfeedback",
            name="additional_problems",
        ),
        migrations.AlterField(
            model_name="teacherfeedback",
            name="km_work_comment",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="teacherfeedback",
            name="tutor_work_comment",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
