# Generated by Django 4.2.3 on 2023-08-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0007_teacherfeedback_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherfeedback",
            name="additional_problems",
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
