# Generated by Django 4.2.3 on 2023-08-02 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0008_teacherfeedback_additional_problems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherfeedback",
            name="problems",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=256), size=None
            ),
        ),
    ]
