# Generated by Django 4.2.3 on 2023-08-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0011_tutorprofile_auth_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="login_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
