# Generated by Django 4.2.3 on 2023-08-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0013_teachercomment_group_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachercomment",
            name="comment_type",
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
