# Generated by Django 4.2.3 on 2023-08-02 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0014_alter_teachercomment_comment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachercomment",
            name="comment_type",
        ),
    ]
