# Generated by Django 4.2.3 on 2023-08-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0015_remove_teachercomment_comment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachercomment",
            name="comment_type",
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
