# Generated by Django 4.2.3 on 2023-08-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0016_teachercomment_comment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
