# Generated by Django 4.2.3 on 2023-08-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0017_alter_teacherprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherfeedback",
            name="lesson_mark",
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
