# Generated by Django 4.2.3 on 2023-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0020_alter_teacherfeedback_additional_problems"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherfeedback",
            name="km_work_mark",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name="teacherfeedback",
            name="tutor_work_mark",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
