# Generated by Django 4.2.3 on 2023-08-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0021_teacherfeedback_km_work_mark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherfeedback",
            name="technical_problems",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
