# Generated by Django 4.2.3 on 2023-08-07 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logika_teachers", "0022_alter_teacherfeedback_technical_problems"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalTutorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("one_c_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "auth_token",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "login_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "related_tutors",
                    models.ManyToManyField(
                        related_name="related_regional_tutors",
                        to="logika_teachers.tutorprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="regional_tutor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
