# Generated by Django 4.2.3 on 2023-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0024_alter_teacherfeedback_predicted_churn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherfeedback",
            name="predicted_churn",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
