# Generated by Django 4.2.3 on 2023-08-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0028_teacherfeedback_commented_churn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachercomment",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="teacherfeedback",
            name="additional_problems",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacherfeedback",
            name="km_work_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacherfeedback",
            name="mistakes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="teacherfeedback",
            name="technical_problems",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacherfeedback",
            name="tutor_work_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
