# Generated by Django 4.2.3 on 2023-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0030_tutormonthreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutormonthreport",
            name="month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
