# Generated by Django 4.2.3 on 2023-08-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0031_tutormonthreport_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutormonthreport",
            name="tutor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="logika_teachers.tutorprofile",
            ),
            preserve_default=False,
        ),
    ]
