# Generated by Django 4.2.3 on 2023-08-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_teachers", "0032_tutormonthreport_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutormonthreport",
            name="category",
            field=models.CharField(default="B", max_length=20),
        ),
    ]
