# Generated by Django 4.2.3 on 2024-08-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logika_statistics', '0014_alter_consolidationreport_group_id_and_more'),
        ('logika_teachers', '0034_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercomment',
            name='lesson_id',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='PredictedChurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churn_id', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('relevant', 'Актуальний'), ('not relevant', 'Неактуальний'), ('churn', 'Відвал')], default='relevant', max_length=16)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logika_teachers.teachercomment')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='predicted_churns', to='logika_teachers.teacherfeedback')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='predicted_churns', to='logika_statistics.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='predicted_churns', to='logika_teachers.teacherprofile')),
            ],
        ),
    ]
