# Generated by Django 4.2.3 on 2024-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logika_teachers', '0035_teachercomment_lesson_id_predictedchurn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'ordering': ('user__last_name', 'user__first_name')},
        ),
        migrations.AddField(
            model_name='predictedchurn',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
