# Generated by Django 4.2.3 on 2024-09-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logika_statistics', '0015_officeregion_alter_group_lms_id_group_office'),
        ('logika_teachers', '0036_alter_tutorprofile_options_predictedchurn_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='offices',
            field=models.ManyToManyField(related_name='tutors', to='logika_statistics.officeregion'),
        ),
        migrations.AlterField(
            model_name='predictedchurn',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_churns', to='logika_statistics.group'),
        ),
        migrations.AlterUniqueTogether(
            name='predictedchurn',
            unique_together={('churn_id', 'teacher')},
        ),
    ]
