# Generated by Django 4.2.3 on 2024-09-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logika_teachers', '0037_tutorprofile_offices_alter_predictedchurn_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedchurn',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_churns', to='logika_teachers.tutorprofile'),
        ),
        migrations.AlterField(
            model_name='predictedchurn',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_churns', to='logika_teachers.teacherfeedback'),
        ),
        migrations.AlterField(
            model_name='predictedchurn',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_churns', to='logika_teachers.teacherprofile'),
        ),
    ]
