# Generated by Django 4.2.3 on 2023-08-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lms_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                (
                    "venue",
                    models.CharField(
                        blank=True, default="not_set", max_length=255, null=True
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("approximate_end_date", models.DateField(blank=True, null=True)),
                ("course_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
