# Generated by Django 4.2.3 on 2023-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "logika_statistics",
            "0002_clientmanagerreport_coursereport_globalgroup_issue_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="teacher_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
