# Generated by Django 4.2.3 on 2023-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_statistics", "0003_group_teacher_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterClassRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_lms_id", models.CharField(max_length=16)),
                ("student_lms_name", models.CharField(max_length=128)),
                ("mc_lms_id", models.CharField(max_length=16)),
                ("mc_date", models.DateField()),
                (
                    "business",
                    models.CharField(
                        choices=[
                            ("programming", "Програмування"),
                            ("english", "Англійська"),
                        ],
                        max_length=16,
                    ),
                ),
                ("location", models.CharField(max_length=128)),
                ("teacher", models.CharField(max_length=128)),
                ("tutor", models.CharField(max_length=128)),
                ("client_manager", models.CharField(max_length=128)),
                ("territorial_manager", models.CharField(max_length=128)),
                ("regional_manager", models.CharField(max_length=128)),
            ],
        ),
    ]
