# Generated by Django 4.2.3 on 2023-12-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_statistics", "0006_remove_masterclassrecord_enrolled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="masterclassrecord",
            name="mc_date",
        ),
        migrations.AddField(
            model_name="masterclassrecord",
            name="end_date",
            field=models.DateField(default="2023-11-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="masterclassrecord",
            name="start_date",
            field=models.DateField(default="2023-11-01"),
            preserve_default=False,
        ),
    ]
