# Generated by Django 4.2.3 on 2023-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_statistics", "0007_remove_masterclassrecord_mc_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterclassrecord",
            name="is_uk",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
