# Generated by Django 4.2.3 on 2023-12-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_statistics", "0008_masterclassrecord_is_uk"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_lms_id", models.CharField(max_length=16)),
                ("student_lms_name", models.CharField(max_length=128)),
                ("mc_lms_id", models.CharField(max_length=16)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "business",
                    models.CharField(
                        choices=[
                            ("programming", "Програмування"),
                            ("english", "Англійська"),
                            ("unknown", "Невідомий"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("location", models.CharField(max_length=128, null=True)),
                ("teacher", models.CharField(max_length=128, null=True)),
                ("teacher_lms_id", models.CharField(max_length=16, null=True)),
                ("tutor", models.CharField(max_length=128, null=True)),
                ("client_manager", models.CharField(max_length=128, null=True)),
                ("territorial_manager", models.CharField(max_length=128, null=True)),
                ("regional_manager", models.CharField(max_length=128, null=True)),
                ("course_title", models.CharField(max_length=128, null=True)),
                ("course_id", models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="masterclassrecord",
            name="business",
            field=models.CharField(
                choices=[
                    ("programming", "Програмування"),
                    ("english", "Англійська"),
                    ("unknown", "Невідомий"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
