# Generated by Django 4.2.3 on 2023-12-17 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "logika_statistics",
            "0010_rename_mc_lms_id_masterclassrecord_recent_group_lms_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentrecord",
            name="tutor",
        ),
    ]
