# Generated by Django 4.2.3 on 2024-01-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "logika_statistics",
            "0012_rename_recent_group_lms_id_masterclassrecord_mc_lms_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsolidationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=256, null=True)),
                ("group_id", models.CharField(blank=True, max_length=16, null=True)),
                ("student_id", models.CharField(blank=True, max_length=16, null=True)),
                ("payment_total", models.IntegerField(null=True)),
                ("lms_total", models.IntegerField(null=True)),
                (
                    "group_title",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("difference", models.IntegerField()),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("status", models.CharField(default="todo", max_length=256, null=True)),
                ("comment", models.TextField(null=True)),
                ("type", models.CharField(max_length=256)),
            ],
        ),
    ]
