# Generated by Django 4.2.3 on 2024-01-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logika_statistics", "0013_consolidationreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consolidationreport",
            name="group_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="consolidationreport",
            name="student_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
