# Generated by Django 4.2.3 on 2024-09-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logika_statistics', '0014_alter_consolidationreport_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='lms_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='office',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='logika_statistics.officeregion'),
        ),
    ]
