# Generated by Django 4.2.3 on 2024-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logika_statistics', '0015_officeregion_alter_group_lms_id_group_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclassrecord',
            name='new_lms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
