# Generated by Django 4.2.3 on 2025-01-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logika_statistics', '0016_masterclassrecord_new_lms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=50)),
                ('error_msg', models.TextField()),
                ('additional_filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='new_lms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
